#!/bin/bash
sudo apt-get install software-properties-common python-software-properties -y
sudo add-apt-repository ppa:ansible/ansible -y
sudo apt-get update && sudo apt-get install ansible -y
cd
git clone https://github.com/andreipak/wordpress-ansible.git
cd wordpress-ansible  
sudo ansible-playbook playbook.yml -i hosts -e mysql_root_password=#password#

